# ЛР 1 — Завдання 2.1: Попередня обробка даних

**Бінаризація, виключення середнього, масштабування, нормалізація** (Google Colab варіант)

### Мета
Показати ключові прийоми попередньої обробки та інтерпретувати результат.

In [2]:

import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt
%matplotlib inline

# Вихідні дані
input_data = np.array([
    [5.1, -2.9,  3.3],
    [-1.2, 7.8, -6.1],
    [3.9,  0.4,  2.1],
    [7.3, -9.9, -4.5]
], dtype=float)

print("Дані:\n", input_data)


Дані:
 [[ 5.1 -2.9  3.3]
 [-1.2  7.8 -6.1]
 [ 3.9  0.4  2.1]
 [ 7.3 -9.9 -4.5]]


#### 1) Бінаризація (поріг 2.1)

In [3]:

binarizer = preprocessing.Binarizer(threshold=2.1)
data_binarized = binarizer.transform(input_data)
print("Binarized data:\n", data_binarized)


Binarized data:
 [[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


#### 2) Виключення середнього (z-score)

In [4]:

print("BEFORE: mean:", input_data.mean(axis=0), " std:", input_data.std(axis=0))
data_scaled = preprocessing.scale(input_data)
print("AFTER : mean:", data_scaled.mean(axis=0), " std:", data_scaled.std(axis=0))


BEFORE: mean: [ 3.775 -1.15  -1.3  ]  std: [3.12039661 6.36651396 4.0620192 ]
AFTER : mean: [1.11022302e-16 0.00000000e+00 2.77555756e-17]  std: [1. 1. 1.]


#### 3) Масштабування Min–Max до [0,1]

In [5]:

mm = preprocessing.MinMaxScaler((0,1))
data_minmax = mm.fit_transform(input_data)
print("Min–max scaled:\n", data_minmax)


Min–max scaled:
 [[0.74117647 0.39548023 1.        ]
 [0.         1.         0.        ]
 [0.6        0.5819209  0.87234043]
 [1.         0.         0.17021277]]


#### 4) Нормалізація L1 та L2

In [6]:

l1 = preprocessing.normalize(input_data, norm='l1')
l2 = preprocessing.normalize(input_data, norm='l2')
print("L1:\n", l1)
print("\nL2:\n", l2)

print("\nВисновок: L1 стійкіша до викидів (нормує суму модулів до 1), L2 — суму квадратів до 1.")


L1:
 [[ 0.45132743 -0.25663717  0.2920354 ]
 [-0.0794702   0.51655629 -0.40397351]
 [ 0.609375    0.0625      0.328125  ]
 [ 0.33640553 -0.4562212  -0.20737327]]

L2:
 [[ 0.75765788 -0.43082507  0.49024922]
 [-0.12030718  0.78199664 -0.61156148]
 [ 0.87690281  0.08993875  0.47217844]
 [ 0.55734935 -0.75585734 -0.34357152]]

Висновок: L1 стійкіша до викидів (нормує суму модулів до 1), L2 — суму квадратів до 1.
