In [1]:

import numpy as np
from sklearn import preprocessing

values = [-3.3, -1.6, 6.1, 2.4, -1.2, 4.3, -3.2, 5.5, -6.1, -4.4, 1.4, -1.2, 2.1]
threshold = float(values[-1])
vals = np.array(values[:-1], dtype=float)
assert vals.size % 3 == 0
input_data_new = vals.reshape((-1, 3))
binarized = preprocessing.Binarizer(threshold=threshold).transform(input_data_new)
print(binarized)
scaled = preprocessing.scale(input_data_new)
print(scaled.mean(axis=0))
print(scaled.std(axis=0))
minmax = preprocessing.MinMaxScaler((0,1)).fit_transform(input_data_new)
print(minmax)
norm_l1 = preprocessing.normalize(input_data_new, norm='l1')
norm_l2 = preprocessing.normalize(input_data_new, norm='l2')
print(norm_l1)
print(norm_l2)


[[0. 0. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [0. 0. 0.]]
[ 2.77555756e-17 -5.55111512e-17  6.93889390e-17]
[1. 1. 1.]
[[0.16176471 0.         1.        ]
 [1.         0.05633803 0.85245902]
 [0.17647059 1.         0.        ]
 [0.         0.42253521 0.40163934]]
[[-0.3        -0.14545455  0.55454545]
 [ 0.30379747 -0.15189873  0.5443038 ]
 [-0.21621622  0.37162162 -0.41216216]
 [-0.62857143  0.2        -0.17142857]]
[[-0.46364048 -0.22479538  0.8570324 ]
 [ 0.47351004 -0.23675502  0.84837215]
 [-0.36302745  0.62395344 -0.69202108]
 [-0.92228798  0.29345527 -0.25153308]]
