In [1]:

import numpy as np
from sklearn import preprocessing

input_data = np.array([[5.1, -2.9, 3.3],
                       [-1.2, 7.8, -6.1],
                       [3.9, 0.4, 2.1],
                       [7.3, -9.9, -4.5]], dtype=float)
data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print(data_binarized)
print(input_data.mean(axis=0))
print(input_data.std(axis=0))
data_scaled = preprocessing.scale(input_data)
print(data_scaled.mean(axis=0))
print(data_scaled.std(axis=0))
mm = preprocessing.MinMaxScaler((0,1)).fit_transform(input_data)
print(mm)
l1 = preprocessing.normalize(input_data, norm='l1')
l2 = preprocessing.normalize(input_data, norm='l2')
print(l1)
print(l2)


[[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[ 3.775 -1.15  -1.3  ]
[3.12039661 6.36651396 4.0620192 ]
[1.11022302e-16 0.00000000e+00 2.77555756e-17]
[1. 1. 1.]
[[0.74117647 0.39548023 1.        ]
 [0.         1.         0.        ]
 [0.6        0.5819209  0.87234043]
 [1.         0.         0.17021277]]
[[ 0.45132743 -0.25663717  0.2920354 ]
 [-0.0794702   0.51655629 -0.40397351]
 [ 0.609375    0.0625      0.328125  ]
 [ 0.33640553 -0.4562212  -0.20737327]]
[[ 0.75765788 -0.43082507  0.49024922]
 [-0.12030718  0.78199664 -0.61156148]
 [ 0.87690281  0.08993875  0.47217844]
 [ 0.55734935 -0.75585734 -0.34357152]]


In [2]:

from sklearn import preprocessing as prep
input_labels = ['red', 'black', 'red', 'green', 'black', 'yellow', 'white']
encoder = prep.LabelEncoder().fit(input_labels)
for i, item in enumerate(encoder.classes_):
    print(item, i)
test_labels = ['green', 'red', 'black']
print(encoder.transform(test_labels))
print(list(encoder.inverse_transform([3,0,1])))


black 0
green 1
red 2
white 3
yellow 4
[1 2 0]
[np.str_('white'), np.str_('black'), np.str_('green')]
