# ЛР 1 — Завдання 2.2: Попередня обробка **нових даних** за варіантом

In [2]:

import numpy as np
from sklearn import preprocessing

values = [-3.3, -1.6, 6.1, 2.4, -1.2, 4.3, -3.2, 5.5, -6.1, -4.4, 1.4, -1.2]
threshold = 2.1

input_data = np.array(values, dtype=float).reshape(-1,3)
print("Дані (Nx3):\n", input_data)


Дані (Nx3):
 [[-3.3 -1.6  6.1]
 [ 2.4 -1.2  4.3]
 [-3.2  5.5 -6.1]
 [-4.4  1.4 -1.2]]


#### 1) Бінаризація

In [3]:

data_bin = preprocessing.Binarizer(threshold=threshold).transform(input_data)
print("Binarized:\n", data_bin)


Binarized:
 [[0. 0. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [0. 0. 0.]]


#### 2) Виключення середнього

In [4]:

print("BEFORE mean:", input_data.mean(axis=0), " std:", input_data.std(axis=0))
data_scaled = preprocessing.scale(input_data)
print("AFTER  mean:", data_scaled.mean(axis=0), " std:", data_scaled.std(axis=0))


BEFORE mean: [-2.125  1.025  0.775]  std: [2.65459507 2.82875856 4.79446295]
AFTER  mean: [ 2.77555756e-17 -5.55111512e-17  6.93889390e-17]  std: [1. 1. 1.]


#### 3) Масштабування Min–Max

In [5]:

mm = preprocessing.MinMaxScaler((0,1))
data_mm = mm.fit_transform(input_data)
print("Min–Max:\n", data_mm)


Min–Max:
 [[0.16176471 0.         1.        ]
 [1.         0.05633803 0.85245902]
 [0.17647059 1.         0.        ]
 [0.         0.42253521 0.40163934]]


#### 4) Нормалізація L1/L2

In [6]:

l1 = preprocessing.normalize(input_data, 'l1')
l2 = preprocessing.normalize(input_data, 'l2')
print("L1:\n", l1)
print("\nL2:\n", l2)


L1:
 [[-0.3        -0.14545455  0.55454545]
 [ 0.30379747 -0.15189873  0.5443038 ]
 [-0.21621622  0.37162162 -0.41216216]
 [-0.62857143  0.2        -0.17142857]]

L2:
 [[-0.46364048 -0.22479538  0.8570324 ]
 [ 0.47351004 -0.23675502  0.84837215]
 [-0.36302745  0.62395344 -0.69202108]
 [-0.92228798  0.29345527 -0.25153308]]


Висновок:
Дані успішно оброблено. Після бінаризації, масштабування й нормалізації всі значення приведено до зручного діапазону та готові для подальшого аналізу.